
package cliente.clube;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SEIClube", targetNamespace = "http://servico/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SEIClube {


    /**
     * 
     * @param arg0
     * @return
     *     returns cliente.clube.Clube
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClube", targetNamespace = "http://servico/", className = "cliente.clube.GetClube")
    @ResponseWrapper(localName = "getClubeResponse", targetNamespace = "http://servico/", className = "cliente.clube.GetClubeResponse")
    @Action(input = "http://servico/SEIClube/getClubeRequest", output = "http://servico/SEIClube/getClubeResponse")
    public Clube getClube(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cliente.clube.Clube>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClubes", targetNamespace = "http://servico/", className = "cliente.clube.GetClubes")
    @ResponseWrapper(localName = "getClubesResponse", targetNamespace = "http://servico/", className = "cliente.clube.GetClubesResponse")
    @Action(input = "http://servico/SEIClube/getClubesRequest", output = "http://servico/SEIClube/getClubesResponse")
    public List<Clube> getClubes();

}
