
package br.com.ws.crud.jaxws.servico;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SEINoticia", targetNamespace = "http://servico.jaxws.crud.ws.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SEINoticia {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "criar", targetNamespace = "http://servico.jaxws.crud.ws.com.br/", className = "br.com.ws.crud.jaxws.servico.Criar")
    @ResponseWrapper(localName = "criarResponse", targetNamespace = "http://servico.jaxws.crud.ws.com.br/", className = "br.com.ws.crud.jaxws.servico.CriarResponse")
    @Action(input = "http://servico.jaxws.crud.ws.com.br/SEINoticia/criarRequest", output = "http://servico.jaxws.crud.ws.com.br/SEINoticia/criarResponse")
    public boolean criar(
        @WebParam(name = "arg0", targetNamespace = "")
        Noticia arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alterar", targetNamespace = "http://servico.jaxws.crud.ws.com.br/", className = "br.com.ws.crud.jaxws.servico.Alterar")
    @ResponseWrapper(localName = "alterarResponse", targetNamespace = "http://servico.jaxws.crud.ws.com.br/", className = "br.com.ws.crud.jaxws.servico.AlterarResponse")
    @Action(input = "http://servico.jaxws.crud.ws.com.br/SEINoticia/alterarRequest", output = "http://servico.jaxws.crud.ws.com.br/SEINoticia/alterarResponse")
    public boolean alterar(
        @WebParam(name = "arg0", targetNamespace = "")
        Noticia arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletar", targetNamespace = "http://servico.jaxws.crud.ws.com.br/", className = "br.com.ws.crud.jaxws.servico.Deletar")
    @ResponseWrapper(localName = "deletarResponse", targetNamespace = "http://servico.jaxws.crud.ws.com.br/", className = "br.com.ws.crud.jaxws.servico.DeletarResponse")
    @Action(input = "http://servico.jaxws.crud.ws.com.br/SEINoticia/deletarRequest", output = "http://servico.jaxws.crud.ws.com.br/SEINoticia/deletarResponse")
    public boolean deletar(
        @WebParam(name = "arg0", targetNamespace = "")
        Noticia arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.ws.crud.jaxws.servico.Noticia
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ler", targetNamespace = "http://servico.jaxws.crud.ws.com.br/", className = "br.com.ws.crud.jaxws.servico.Ler")
    @ResponseWrapper(localName = "lerResponse", targetNamespace = "http://servico.jaxws.crud.ws.com.br/", className = "br.com.ws.crud.jaxws.servico.LerResponse")
    @Action(input = "http://servico.jaxws.crud.ws.com.br/SEINoticia/lerRequest", output = "http://servico.jaxws.crud.ws.com.br/SEINoticia/lerResponse")
    public Noticia ler(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<br.com.ws.crud.jaxws.servico.Noticia>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listar", targetNamespace = "http://servico.jaxws.crud.ws.com.br/", className = "br.com.ws.crud.jaxws.servico.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://servico.jaxws.crud.ws.com.br/", className = "br.com.ws.crud.jaxws.servico.ListarResponse")
    @Action(input = "http://servico.jaxws.crud.ws.com.br/SEINoticia/listarRequest", output = "http://servico.jaxws.crud.ws.com.br/SEINoticia/listarResponse")
    public List<Noticia> listar();

}
